apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hello-world-py
  janus-idp.io/tekton: hello-world-py
  backstage.io/kubernetes-id: hello-world-py
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: hello-world-py
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
