apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: hello-world-py
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hello-world-py 
  name: hello-world-py
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: hello-world-py
    weight: 100 
