apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hello-world-py
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hello-world-py 
  name: hello-world-py
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hello-world-py 
