apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: hello-world-py
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhads-jowilkin/hello-world:0d50e48c20e39119bc4e7b73fe547a17a7059add@sha256:7815f50e99700b1a3f76e3fbf598090a8650088d3e54698c829317ab41fd6f1c
          name: container-image
